### ISSUE TITLE
Support both Javascript and Typescript base image

### ISSUE THREAD

**Issue by ghost** [pcs-publishing/devcontainer-node#3]
```
As a developer
I want to be able to choose Javascript or Typescript as the base container
So that I don't need multiple templates
```

In `.devcontainer/Dockerfile.devcontainer` we specify the base image to build our `devcontainer` environment from.

Microsoft provide a huge selection of base containers [here](https://github.com/microsoft/vscode-dev-containers). One of which is [javascript-node](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/javascript-node), with another that is [typescript-node](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/typescript-node).

You can switch between them simply by changing the base image we build from to one of the following: 

- `mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14-bullseye`
- `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-bullseye`

Careful use of environment variables would allow the developer to configure his own environment to use either Javascript or Typescript as the base tool set:

In `.devcontainer/Dockerfile.devcontainer`:

```
ARG VARIANT
ARG FLAVOUR
FROM mcr.microsoft.com/vscode/devcontainers/${FLAVOUR}-node:0-${VARIANT}
```

And, in `.devcontainer/docker-compose.devcontainer`:

```
build:
      context: ..
      args:
        - VARIANT=${NODE_VERSION:-16}-${OS_VERSION:-bullseye}
        - FLAVOUR=${LANGUAGE:-javascript}
      dockerfile: .devcontainer/Dockerfile.devcontainer
```

We won't need a separate Typescript variant of the repository if we can add support for this. It would make sense to re-name the repository itself to the more generic `devcontainer-node` too.

- [x] Effect the changes listed above

- [x] Change the repository name to `devcontinaer-node`

- [x] Update forks and remotes to use the new name
